apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: timescalers.engineerkenji.com
spec:
  group: engineerkenji.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                startTime:
                  type: integer
                endTime:
                  type: integer
                replicas:
                  type: integer
                deployment:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
  scope: Namespaced
  names:
    plural: timescalers
    singular: timescaler
    kind: TimeScaler
    shortNames:
    - ts